version: "3.3"

services:
  db:
    image: postgres:10.10-alpine
    environment:
      POSTGRES_USER: jdisctf
      POSTGRES_PASSWORD: jdisctf
      POSTGRES_DB: jdisctf_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  
  migration:
    environment:
      FLASK_APP: main.py
      POSTGRES_URL: db:5432
      POSTGRES_USER: jdisctf
      POSTGRES_PW: jdisctf
      POSTGRES_DB: jdisctf_db
    build: ./backend
    command: sh -c "sleep 10s && flask db upgrade"
    depends_on:
      - db
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - frontend-user
      - frontend-admin
      - backend

  backend:
    build: ./backend
    restart: always

  frontend-user:
    build: ./frontend/user
    restart: always

  frontend-admin:
    build: ./frontend/admin
    restart: always
