name: 'Build a Dockerfile'
description: 'Builds the provided Docker image'
inputs:
  dockerfile:
    description: 'Dockerfile to build'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: ${{ inputs.dockerfile}}
