name: Continuous Integration

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Lint Frontend USER
      working-directory: ./frontend/user
      run: |
        npm ci
        npm run lint
      env:
        CI: true

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build Backend
      run: docker build ./backend

    - name: Build Frontend USER
      run: docker build ./frontend/user
    
    - name: Build Frontend ADMIN
      run: docker build ./frontend/admin
