name: Continuous Integration

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Lint Frontend USER
        run: npm run lint
        working-directory: ./frontend/user

      - name: Lint Frontend ADMIN
        run: npm run lint
        working-directory: ./frontend/admin

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build Backend
      run: docker build ./backend

    - name: Build Frontend USER
      run: docker build ./frontend/user
    
    - name: Build Frontend ADMIN
      run: docker build ./frontend/admin
