name: CI

on: [push, pull_request]

jobs:
  build-frontend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
      
    - name: Lint Backend
      run: |
        apt install python3-setuptools
        pip3 install pylint
        pylint JDISCTF seeds
      working-directory: ./backend
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and build USER
      working-directory: ./frontend/user
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true

    - name: npm install and build ADMIN
      working-directory: ./frontend/admin
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
